run:
  timeout: 3m
  go: "1.24"

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - revive
    - misspell
    - errcheck

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: errorf
        - name: var-declaration
        - name: ban-unused-imports
    gofmt:
      simplify: true
    misspell:
      locale: US
